### ISSUE TITLE
docker_compose_v2 module is not idempotent when using "build: always"

### ISSUE THREAD

**Issue by definitio** [ansible-collections/community.docker#1005]
##### SUMMARY

Task returns `"changed": true` when using `build: always` even when images are not rebuilt.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_compose_v2

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.1]
  config file = path/to/ansible.cfg
  configured module search path = ['/home/m/.cache/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/m/.cache/ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection       Version
---------------- -------
community.docker 4.1.0
```

##### CONFIGURATION

```paste below
ANSIBLE_HOME(env: ANSIBLE_HOME) = /home/$USERNAME/.cache/ansible
CONFIG_FILE() = None
DEFAULT_LOCAL_TMP(env: ANSIBLE_LOCAL_TEMP) = /home/$USERNAME/.cache/ansible-tmp/ansible-local-63942m_nsfyzt
EDITOR(env: EDITOR) = micro
PAGER(env: PAGER) = less
```

##### STEPS TO REPRODUCE

```yaml
community.docker.docker_compose_v2:
        build: always
```

##### EXPECTED RESULTS

Expected `"changed": false` when images are not rebuilt.

##### ACTUAL RESULTS

Got `"changed": true`

```paste below
changed: [$HOST] =>
  docker_output.actions:
  - id: $CONTAINER
    status: Building
    what: service
```

**Comment by felixfontein** [comment]
From the output you posted the image *has been* rebuilt. I guess you mean that the rebuilt image is identical to the image that was already there?

**Comment by definitio** [comment]
Yes. It was built but not used because it's identical to already running.

**Comment by felixfontein** [comment]
Changing the behavior only makes sense when `state=present` (and outside check mode), since in the other cases it's not possible to detect whether the container is actually recreated.

Since the current behavior has been the default since creation of the module, I'm currently tending to make this configurable (i.e. allow to ignore build actions for the changed status).

**Comment by definitio** [comment]
Only `state=present` can trigger containers building because `docker compose up` has `--build` and `stop`, `down`, `restart` hasn't it. Checking whether the container is actually recreated or not is useful only for this state. That's probably was behavior of docker-compose v.1 module. At least it doesn't return `"changed": true` when the container is not recreated.
IMHO it's more useful to return `"changed": true` when the container is actually recreated. Can the new option ignore only build actions without container recreating?

**Comment by felixfontein** [comment]
Interestingly this is only a problem with Compose 2.31.0 or newer (released two weeks ago), since that's the first version that actually build events. (Changelog: https://github.com/docker/compose/releases.) Before that build events were only emitted in dry runs - but in dry run it always says it restarts the container anyway.
